name: Game Thread Updater

on:
  schedule:
    - cron: '*/10 0-3,12 * * 4' # Thursdays, every 10-minutes between 8pm-1am ET
    - cron: '*/10 17-23 * * 0' # Sundays, every 10-minutes between 1pm-Midnight ET
    - cron: '*/10 * * * 1' # Mondays, every 10-minutes between 8pm-1am ET
  workflow_dispatch:  # This allows you to manually trigger the workflow from the GitHub Actions UI

jobs:
  update-game-thread:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run gamethread-updater.py
      run: python gamethread-updater.py
      env:
        SQUABBLES_TOKEN: ${{ secrets.SQUABBLES_TOKEN }}
        NFLBOT_WRITE_TO_GIST: ${{ secrets.NFLBOT_WRITE_TO_GIST }}  # Using the GitHub token from repository secrets
