name: Game Thread Poster

on:
  workflow_dispatch:  # This allows you to manually trigger the workflow from the GitHub Actions UI

jobs:
  post-game-thread:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Add any other dependencies if required

    - name: Run test-gamethread-poster.py
      run: python test-gamethread-poster.py
      env:
        SQUABBLES_TOKEN: ${{ secrets.SQUABBLES_TOKEN }}
