
name: NFL Schedule Creation Bot (Gist Update)

on:
  workflow_dispatch:

jobs:
  update_schedule:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Run schedule-creation-bot-gist.py
      run: python .github/schedule-creation-bot-gist.py
      env:
        NFLBOT_WRITE_TO_GIST: ${{ secrets.GH_TOKEN }}  # Using the GitHub token from repository secrets
