name: Weekly Schedule Poster

on:
  schedule:
    - cron: '0 12 * * 3' # At 12:00 PM UTC (8am ET) every Wednesday
  workflow_dispatch:  # This allows you to manually trigger the workflow from the GitHub Actions UI

jobs:
  post-weekly-schedule:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run weekly-schedule-poster.py
      run: python weekly-schedule-poster.py
      env:
        SQUABBLES_TOKEN: ${{ secrets.SQUABBLES_TOKEN }}
