name: Weekly Schedule Poster

on:
  # schedule:
  #  - cron: '0 13 * * 3'  # Runs at 9am ET every Wednesday
  workflow_dispatch:  

jobs:
  post_weekly_schedule:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas pytz requests

    - name: Run weekly-schedule-poster script
      run: python ./weekly-schedule-poster.py
      env:
        SQUABBLES_TOKEN: ${{ secrets.SQUABBLES_TOKEN }}
        NFLBOT_WRITE_TO_GIST: ${{ secrets.NFLBOT_WRITE_TO_GIST }}
        NFLBOT_SCHEDULES_GIST: ${{ secrets.NFLBOT_SCHEDULES_GIST }}
        NFLBOT_STANDINGS_GIST: ${{ secrets.NFLBOT_STANDINGS_GIST }}
